### ISSUE TITLE
urxvtc -e pmenu-run does not launch an app

### ISSUE THREAD

**Issue by sirsurthur** [sgtpep/pmenu#1]
Hello and thanks for this software that I like a lot.

I bind pmenu with my wm using the following command : urxvtc -e pmenu-run. When I select an app from the list, pmenu does not launch it. Same problem if I use urxvt -e pmenu-run or xterm -e pmenu-run. 

It works well if I call pmenu-run from urxvtc. Any clue of the mistake I am doing ?

Best wishes,

**Comment by sgtpep** [comment]
Hello! Happy to hear you've found it useful!

Couldn't reproduce this on Arch Linux with ratpoison WM using the code from master.

Does pmenu itself works in this case or it's just the wrapper script pmenu-run? `urxvt -e pmenu foo bar`
By any chance, does this version of command works for you? (With semicolon inside of quotes; I had the similar issue with Openbox with another ncurses software which strangely misbehaved without them.) `urxvt -e bash -c "pmenu-run; "`

**Comment by sgtpep** [comment]
Sorry, ignore the first question and the command from it.

Also suggest to try pmen-run without the word `setsid` in it.  And how does it work without the words `nohup` and `setsid`?

**Comment by sirsurthur** [comment]
Hi sgtpep !
I looked inside pmenu-run and saw that I did not have nohup / setsid. The PKGBUILD in AUR Archlinux seems outdated. Could you update it ? Maybe the latest version already fix the issue.

Thanks a lot and best wishes,

**Comment by sirsurthur** [comment]
I confirm ; If I update, then it fixes the problem !

**Comment by sgtpep** [comment]
Sorry about delay. Yeah, forgot to update the AUR package with the recent code from master. It had been updated. Thanks for noticing!
