### ISSUE TITLE
Question: Any suggestion for a wrapper to save most frequent choice ?

### ISSUE THREAD

**Issue by 4vrel** [sgtpep/pmenu#2]
Hello !
Great work, and also great list of all other pmenu solution.

Do you know any wrapper that I could with with pmenu to save the most frequent choice ?
something like:
command ls /bin/ | foo-sort-by-frequency | pmenu | foo-save-choice-to-db 
Thank you

**Comment by sgtpep** [comment]
Hi @4vrel!

I think, what you're looking for is listed in the list of "dmenu wrappers" here: https://github.com/sgtpep/pmenu#dmenu-wrappers.

Also, `dmenu` itself provides a basic functionality like that with an option `-n NAME, --name NAME`. If it's passed `dmenu` shows most recently selected items on top.
